# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: "3.0.1"
info:
  version: 0.0.1
paths: {}
# We do not use code-generation because we want to have more control over API implementation and url mapping
# But we do generate swagger definitions by working code (please see web ui http://localhost:8080/#/admin/docs)
